repo:
  mock: true
  db: false
  api: false
  
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/manage"
  endpoint:
    info:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true



